<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Anna validi sähköpostiosoite',
'Email legend 2'			=>	'Anna ja vahvista validi sähköpostiosoite',
'Localisation legend'		=>	'Aseta sijaintiasetukset',
'Time zone'					=>	'Aikavyöhyke',
'Time zone info'			=>	'Jotta foorumi näyttää kellonajat oikein, sinun täytyy valita aikavyöhykkeesi. Jos nyt on kesäaika, sinun tulisi valita myös annettu asetus, joka siirtää kellonaikaa tunnilla eteenpäin.',
'DST'						=>	'Kesäaika (siirrä kelloa tunnilla eteenpäin).',
'Time format'				=>	'Ajan muoto',
'Date format'				=>	'Päiväyksen muoto',
'Default'					=>	'Oletus',
'Language'					=>	'Kieli',
'Email setting info'		=>	'Valitse, haluatko sähköpostiosoitteesi näkyvän muille käyttäjille ja onko muiden käyttäjien mahdollista lähettää sinulle sähköpostia foorumin kautta (form email).',
'Email setting 1'			=>	'Näytä sähköpostiosoite.',
'Email setting 2'			=>	'Piilota sähköpostiosoite mutta salli sähköpostin lähetys foorumin kautta.',
'Email setting 3'			=>	'Piilota sähköpostiosoite ja estä sähköpostin lähetys foorumin kautta..',
'Privacy options legend'	=>	'Aseta yksityisyysasetukset',
'Confirm pass'				=>	'Vahvista salasana',

'Username too short'		=>	'Käyttäjänimien tulee olla vähintään 2 merkkiä pitkiä. Valitse pidempi käyttäjänimi.',
'Username too long'			=>	'Käyttäjänimet eivät voi olla yli 25 merkkiä pitkiä. Valitse lyhyempi käyttäjänimi.',
'Username guest'			=>	'Käyttäjänimi guest on varattu. Valitse toinen käyttäjänimi.',
'Username IP'				=>	'Käyttäjänimet eivät voi olla ip-osoitteiden muodossa. Valitse toinen käyttäjänimi.',
'Username reserved chars'	=>	'Käyttäjänimet eivät voi sisältää merkkejä \', " ja [ tai ] samaan aikaan. Ole hyvä ja valitse toinen käyttäjänimi.',
'Username BBCode'			=>	'Käyttäjänimet eivät voi sisältää mitään tekstinmuotoilutageja (BBCode). Ole hyvä ja valitse toinen käyttäjänimi.',
'Banned username'			=>	'Syöttämäsi käyttäjänimi on bannattu tällä foorumilla. Ole hyvä ja valitse toinen käyttäjänimi.',
'Pass too short'			=>	'Salasanojen tulee olla vähintään 4 merkkiä pitkä. Ole hyvä ja valitse pidempi salasana.',
'Pass not match'			=>	'Salasanat eivät täsmää.',
'Banned email'				=>	'Annettu sähköpostiosoite on bannattu tältä foorumilta.Ole hyvä ja anna toinen sähköpostiosoite.',
'Dupe email'				=>	'Joku muu on jo rekisteröitynyt annetulla sähköpostiosoitteella. Ole hyvä ja valitse toinen sähköpostiosoite.',
'Sig too long'				=>	'Allekirjoitukset eivät voi olla %1$s merkkiä pidempiä. Lyhennä allekirjoitustasi %2$s merkillä.',
'Sig too many lines'		=>	'Allekirjoituksessa voi olla maksimissaan %s riviä.',
'Bad ICQ'					=>	'Antamasi ICQ UIN on epäkelpo. Ole hyvä ja palaa takaisin korjataksesi sen.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
