<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profiili',
'Section essentials'			=>	'Yleiset',
'Section personal'				=>	'Henkil&ouml;tiedot',
'Section messaging'				=>	'Viestint&auml;',
'Section personality'			=>	'Identiteetti',
'Section display'				=>	'Mukauttaminen',
'Section privacy'				=>	'Yksityisyysasetukset',
'Section admin'					=>	'Hallinta',

// Miscellaneous
'Username and pass legend'		=>	'Anna k&auml;ytt&auml;j&auml;nimi ja salasana',
'Personal details legend'		=>	'T&auml;yt&auml; henkil&ouml;kohtaiset tietosi',
'Contact details legend'		=>	'T&auml;yt&auml; viestint&auml; tietosi',
'User activity'					=>	'K&auml;ytt&auml;j&auml;n aktiivisuus',
'Paginate info'					=>	'Voit halutessasi valita kuinka monta aihetta ja viesti&auml; n&auml;ytet&auml;&auml;n kerralla.',

// Password stuff
'Pass key bad'					=>	'Salasanan aktivointiavain on virheellinen tai vanhentunut. Ole hyv&auml; ja pyyd&auml; uutta avaintai, mik&auml;li t&auml;m&auml; ei onnistu - ota yhteys yll&auml;pitoon',
'Pass updated'					=>	'Salasanasi on vaihdettu. Voit nyt kirjautua sis&auml;&auml;n uudella salasanalla.',
'Pass updated redirect'			=>	'Salasana vaihdettu. Uudelleenohjataan …',
'Wrong pass'					=>	'V&auml;&auml;r&auml; vanha salasana.',
'Change pass'					=>	'Muuta salasana',
'Change pass legend'			=>	'Sy&ouml;t&auml; ja vahvista uusi salasana',
'Old pass'						=>	'Vanha salasana',
'New pass'						=>	'Uusi salasana',
'Confirm new pass'				=>	'Vahvista uusi salasana',
'Pass info'						=>	'Salasanan t&auml;ytyy olla v&auml;hint&auml;&auml;n 4 merkki&auml; pitk&auml;. Isot ja pienet kirjaimet huomioidaan.',

// Email stuff
'Email key bad'					=>	'Aktivointiavaimesi on virheellinen tai sen voimassaoloaika on p&auml;&auml;ttynyt. Pyyd&auml; s&auml;hk&ouml;postiosoitteen vaihtoa uudelleen. Jos t&auml;m&auml; ep&auml;onnistuu, ota yhteytt&auml; keskustelualueen p&auml;&auml;k&auml;ytt&auml;j&auml;&auml;n.',
'Email updated'					=>	'S&auml;hk&ouml;postiosoitteesi on vaihdettu.',
'Activate email sent'			=>	'Aktivointi s&auml;hk&ouml;posti on l&auml;hetetty valitsemaasi osoitteeseen, viestiss&auml; on ohjeet tilisi aktivoimiseen. Mik&auml;li et saanut s&auml;hk&ouml;postiasi, ota yhteytt&auml; yll&auml;pitoon',
'Email legend'					=>	'Anna uusi s&auml;hk&ouml;postiosoite',
'Email instructions'			=>	'Aktivointilinkki l&auml;hetet&auml;&auml;n uuteen s&auml;hk&ouml;postiosoitteeseen. Sinun t&auml;ytyy avata s&auml;hk&ouml;postiviestin linkki aktivoidaksesi uuden s&auml;hk&ouml;postiosoitteen.',
'Change email'					=>	'Vaihda s&auml;hk&ouml;postiosoite',
'New email'						=>	'Uusi s&auml;hk&ouml;posti',

// Avatar upload stuff
'Avatars disabled'				=>	'P&auml;&auml;k&auml;ytt&auml;j&auml; on est&auml;nyt keskustelukuvakkeiden k&auml;yt&ouml;n.',
'Too large ini'					=>	'Valitsemasi tiedosto on liian suuri ll&auml;hetett&auml;v&auml;ksi. Palvelin ei hyv&auml;ksy l&auml;hetyspyynt&ouml;&auml;si.',
'Partial upload'				=>	'Tiedosto l&auml;hett&auml;minen ep&auml;onnistui. Yrit&auml; uudelleen.',
'No tmp directory'				=>	'PHP ei pystynyt tallentamaan tiedostoa.',
'No file'						=>	'Et ole valinnut tiedostoa l&auml;hetett&auml;v&auml;ksi.',
'Bad type'						=>	'Tiedoston tyyppi virheellinen. Sallitut tyypit ovat: gif, jpeg ja png.',
'Too wide or high'				=>	'Tiedoston leveys tai korkeus on sallittua suurempi',
'Too large'						=>	'Tiedoston koko on liian suuri',
'pixels'						=>	'pikseli&auml;',
'bytes'							=>	'bitti&auml;',
'Move failed'					=>	'Palvelin ei voinut tallentaa tiedostoa. Ota yhteys yll&auml;pitoon',
'Unknown failure'				=>	'Tuntematon virhe, yrit&auml; uudelleen.',
'Avatar upload redirect'		=>	'Avatar siirretty. Uudelleenohjataan...',
'Avatar deleted redirect'		=>	'Avatar poistettu. Uudelleenohjataan...',
'Avatar desc'					=>	'Avatar on pieni kuva joka n&auml;ytet&auml;&auml;n sinun k&auml;ytt&auml;j&auml;tunnuksen alapuolella. Se ei saa olla isompi kuin',
'Upload avatar'					=>	'Siirr&auml; avatar',
'Upload avatar legend'			=>	'Valitse siirrett&auml;v&auml; avatar',
'Delete avatar'					=>	'Poista keskustelukuvake', // only for admins
'File'							=>	'Tiedosto',
'Upload'						=>	'L&auml;het&auml;', // submit button

// Form validation stuff
'Forbidden title'				=>	'Sy&ouml;tt&auml;m&auml;si otsikko sis&auml;lt&auml;&auml; kielletyn sanan. Valitse toinen otsikko.',
'Profile redirect'				=>	'Profiilin tiedot p&auml;ivitetty. Uudelleenohjataan...',

// Profile display stuff
'Users profile'					=>	'%sn profiili',
'Username info'					=>	'K&auml;ytt&auml;j&auml;nimet: %s',
'Email info'					=>	'S&auml;hk&ouml;posti: %s',
'Posts info'					=>	'Viestit: %s',
'Registered info'				=>	'Rekister&ouml;itynyt: %s',
'Last post info'				=>	'Viimeisin viesti: %s',
'Last visit info'				=>	'K&auml;ynyt viimeksi: %s',
'Show posts'					=>	'N&auml;yt&auml; kaikki viestit',
'Show topics'					=>	'N&auml;yt&auml; kaikki aiheet',
'Show subscriptions'			=>	'N&auml;yt&auml; kaikki tilaajat',
'Realname'						=>	'Todellinen nimi',
'Location'						=>	'Asuinpaikka',
'Website'						=>	'Internetsivusto',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Allekirjoitus',
'Sig max size'					=>	'Maksimi pituus: %s merkki&auml; / Maksimi rivim&auml;&auml;r&auml;: %s',
'Avatar legend'					=>	'Aseta avatarin n&auml;kyvyysasetukset',
'Avatar info'					=>	'Avatar on pieni kuva joka n&auml;ytet&auml;&auml;n viesteiss&auml;si. Voit lis&auml;t&auml; avatarin klikkaamalla alapuolella olevaa linkki&auml;.',
'Change avatar'					=>	'Vaihda avatar',
'Signature legend'				=>	'Muotoile allekirjoitus',
'Signature info'				=>	'Allekirjoitus on pieni teksti, joka n&auml;ytet&auml;&auml;n viesteiss&auml;si. Voit laittaa siihen melkein mit&auml; tahansa. Ehk&auml; haluat laittaa lempi lainauksesi tai t&auml;htimerkkisi. Voit k&auml;ytt&auml;&auml; BBCodea allekirjoituksessasi, jos se on sallittua t&auml;ll&auml; foorumilla. Allekirjoituksen muokkaamista varten olevan kent&auml;n alapuolella voit n&auml;hd&auml; mitk&auml; ominaisuudet ovat sallittuja.',
'Sig preview'					=>	'Nykyisen allekirjoituksen esikatselu:',
'No sig'						=>	'Profiilissasi ei ole m&auml;&auml;ritelty allekirjoitusta.',
'Signature quote/code/list/h'	=>	'Lainaus, koodi, listaus ja otsikko BBCodet eiv&auml;t ole sallittuja allekirjoituksissa.',
'Topics per page'				=>	'Aiheet',
'Posts per page'				=>	'Viestit',
'Leave blank'					=>	'J&auml;t&auml; tyhj&auml;ksi k&auml;ytt&auml;&auml;ksesi foorumin oletusta.',
'Subscription legend'			=>	'Aseta tilauksesi asetukst',
'Notify full'					=>	'Include a plain text version of new posts in subscription notification emails.',
'Auto notify full'				=>	'Automatically subscribe to every topic you post in.',
'Show smilies'					=>	'Show smilies as graphic icons.',
'Show images'					=>	'N&auml;yt&auml; kuvat viesteiss&auml;.',
'Show images sigs'				=>	'Show images in user signatures.',
'Show avatars'					=>	'Show user avatars in posts.',
'Show sigs'						=>	'N&auml;yt&auml; k&auml;ytt&auml;j&auml;n allekirjoitukset.',
'Style legend'					=>	'Select your preferred style',
'Styles'						=>	'Tyylit',
'Admin note'					=>	'Admin note',
'Pagination legend'				=>	'Enter your pagination options',
'Post display legend'			=>	'Set your options for viewing posts',
'Post display info'				=>	'If you are on a slow connection, disabling these options, particularly showing images in posts and signatures, will make pages load faster.',
'Instructions'					=>	'When you update your profile, you will be redirected back to this page.',

// Administration stuff
'Group membership legend'		=>	'Valitse k&auml;ytt&auml;j&auml;ryhm&auml;',
'Save'							=>	'Tallenna',
'Set mods legend'				=>	'Aseta moderaattorin oikeudet',
'Moderator in info'				=>	'Choose which forums this user should be allowed to moderate. Note: This only applies to moderators. Administrators always have full permissions in all forums.',
'Update forums'					=>	'P&auml;ivit&auml; keskustelualueet',
'Delete ban legend'				=>	'Poista (toiminto vain p&auml;&auml;k&auml;ytt&auml;j&auml;lle) tai bannaa k&auml;ytt&auml;j&auml;',
'Delete user'					=>	'Poista k&auml;ytt&auml;j&auml;',
'Ban user'						=>	'Bannaa k&auml;ytt&auml;j&auml;',
'Confirm delete legend'			=>	'T&auml;rke&auml;&auml;: lue ennenkuin poistat k&auml;ytt&auml;j&auml;n',
'Confirm delete user'			=>	'Vahvista k&auml;ytt&auml;j&auml;n poistaminen',
'Confirmation info'				=>	'Please confirm that you want to delete the user', // the username will be appended to this string
'Delete warning'				=>	'Warning! Deleted users and/or posts cannot be restored. If you choose not to delete the posts made by this user, the posts can only be deleted manually at a later time.',
'Delete posts'					=>	'Delete any posts and topics this user has made.',
'Delete'						=>	'Delete', // submit button (confirm user delete)
'User delete redirect'			=>	'User deleted. Redirecting …',
'Group membership redirect'		=>	'Group membership saved. Redirecting …',
'Update forums redirect'		=>	'Forum moderator rights updated. Redirecting …',
'Ban redirect'					=>	'Uudelleenohjataan …',
'No delete admin message'		=>	'Administrators cannot be deleted. In order to delete this user, you must first move him/her to a different user group.',

);