<?php

// Language definitions used in both profile.php and register.php
$lang_prof_reg = array(

'Email legend'				=>	'Anna validi s&auml;hk&ouml;postiosoite',
'Email legend 2'			=>	'Anna ja vahvista validi s&auml;hk&ouml;postiosoite',
'Localisation legend'		=>	'Aseta sijaintiasetukset',
'Time zone'					=>	'Aikavy&ouml;hyke',
'Time zone info'			=>	'Jotta foorumi n&auml;ytt&auml;&auml; kellonajat oikein, sinun t&auml;ytyy valita aikavy&ouml;hykkeesi. Jos nyt on kes&auml;aika, sinun tulisi valita my&ouml;s annettu asetus, joka siirt&auml;&auml; kellonaikaa tunnilla eteenp&auml;in.',
'DST'						=>	'Kes&auml;aika (siirr&auml; kelloa tunnilla eteenp&auml;in).',
'Time format'				=>	'Ajan muoto',
'Date format'				=>	'P&auml;iv&auml;yksen muoto',
'Default'					=>	'Oletus',
'Language'					=>	'Kieli',
'Email setting info'		=>	'Valitse, haluatko s&auml;hk&ouml;postiosoitteesi n&auml;kyv&auml;n muille k&auml;ytt&auml;jille ja onko muiden k&auml;ytt&auml;jien mahdollista l&auml;hett&auml;&auml; sinulle s&auml;hk&ouml;postia foorumin kautta (form email).',
'Email setting 1'			=>	'N&auml;yt&auml; s&auml;hk&ouml;postiosoite.',
'Email setting 2'			=>	'Piilota s&auml;hk&ouml;postiosoite mutta salli s&auml;hk&ouml;postin l&auml;hetys foorumin kautta.',
'Email setting 3'			=>	'Piilota s&auml;hk&ouml;postiosoite ja est&auml; s&auml;hk&ouml;postin l&auml;hetys foorumin kautta..',
'Privacy options legend'	=>	'Aseta yksityisyysasetukset',
'Confirm pass'				=>	'Vahvista salasana',

'Username too short'		=>	'K&auml;ytt&auml;j&auml;nimien tulee olla v&auml;hint&auml;&auml;n 2 merkki&auml; pitki&auml;. Valitse pidempi k&auml;ytt&auml;j&auml;nimi.',
'Username too long'			=>	'K&auml;ytt&auml;j&auml;nimet eiv&auml;t voi olla yli 25 merkki&auml; pitki&auml;. Valitse lyhyempi k&auml;ytt&auml;j&auml;nimi.',
'Username guest'			=>	'K&auml;ytt&auml;j&auml;nimi guest on varattu. Valitse toinen k&auml;ytt&auml;j&auml;nimi.',
'Username IP'				=>	'K&auml;ytt&auml;j&auml;nimet eiv&auml;t voi olla ip-osoitteiden muodossa. Valitse toinen k&auml;ytt&auml;j&auml;nimi.',
'Username reserved chars'	=>	'K&auml;ytt&auml;j&auml;nimet eiv&auml;t voi sis&auml;lt&auml;&auml; merkkej&auml; \', " ja [ tai ] samaan aikaan. Ole hyv&auml; ja valitse toinen k&auml;ytt&auml;j&auml;nimi.',
'Username BBCode'			=>	'K&auml;ytt&auml;j&auml;nimet eiv&auml;t voi sis&auml;lt&auml;&auml; mit&auml;&auml;n tekstinmuotoilutageja (BBCode). Ole hyv&auml; ja valitse toinen k&auml;ytt&auml;j&auml;nimi.',
'Banned username'			=>	'Sy&ouml;tt&auml;m&auml;si k&auml;ytt&auml;j&auml;nimi on bannattu t&auml;ll&auml; foorumilla. Ole hyv&auml; ja valitse toinen k&auml;ytt&auml;j&auml;nimi.',
'Pass too short'			=>	'Salasanojen tulee olla v&auml;hint&auml;&auml;n 4 merkki&auml; pitk&auml;. Ole hyv&auml; ja valitse pidempi salasana.',
'Pass not match'			=>	'Salasanat eiv&auml;t t&auml;sm&auml;&auml;.',
'Banned email'				=>	'Annettu s&auml;hk&ouml;postiosoite on bannattu t&auml;lt&auml; foorumilta.Ole hyv&auml; ja anna toinen s&auml;hk&ouml;postiosoite.',
'Dupe email'				=>	'Joku muu on jo rekister&ouml;itynyt annetulla s&auml;hk&ouml;postiosoitteella. Ole hyv&auml; ja valitse toinen s&auml;hk&ouml;postiosoite.',
'Sig too long'				=>	'Allekirjoitukset eiv&auml;t voi olla %1$s merkki&auml; pidempi&auml;. Lyhenn&auml; allekirjoitustasi %2$s merkill&auml;.',
'Sig too many lines'		=>	'Allekirjoituksessa voi olla maksimissaan %s rivi&auml;.',
'Bad ICQ'					=>	'Antamasi ICQ UIN on ep&auml;kelpo. Ole hyv&auml; ja palaa takaisin korjataksesi sen.',

'UTC-12:00'					=>	'(UTC-12:00) International Date Line West',
'UTC-11:00'					=>	'(UTC-11:00) Niue, Samoa',
'UTC-10:00'					=>	'(UTC-10:00) Hawaii-Aleutian, Cook Island',
'UTC-09:30'					=>	'(UTC-09:30) Marquesas Islands',
'UTC-09:00'					=>	'(UTC-09:00) Alaska, Gambier Island',
'UTC-08:30'					=>	'(UTC-08:30) Pitcairn Islands',
'UTC-08:00'					=>	'(UTC-08:00) Pacific',
'UTC-07:00'					=>	'(UTC-07:00) Mountain',
'UTC-06:00'					=>	'(UTC-06:00) Central',
'UTC-05:00'					=>	'(UTC-05:00) Eastern',
'UTC-04:00'					=>	'(UTC-04:00) Atlantic',
'UTC-03:30'					=>	'(UTC-03:30) Newfoundland',
'UTC-03:00'					=>	'(UTC-03:00) Amazon, Central Greenland',
'UTC-02:00'					=>	'(UTC-02:00) Mid-Atlantic',
'UTC-01:00'					=>	'(UTC-01:00) Azores, Cape Verde, Eastern Greenland',
'UTC'						=>	'(UTC) Western European, Greenwich',
'UTC+01:00'					=>	'(UTC+01:00) Central European, West African',
'UTC+02:00'					=>	'(UTC+02:00) Eastern European, Central African',
'UTC+03:00'					=>	'(UTC+03:00) Moscow, Eastern African',
'UTC+03:30'					=>	'(UTC+03:30) Iran',
'UTC+04:00'					=>	'(UTC+04:00) Gulf, Samara',
'UTC+04:30'					=>	'(UTC+04:30) Afghanistan',
'UTC+05:00'					=>	'(UTC+05:00) Pakistan, Yekaterinburg',
'UTC+05:30'					=>	'(UTC+05:30) India, Sri Lanka',
'UTC+05:45'					=>	'(UTC+05:45) Nepal',
'UTC+06:00'					=>	'(UTC+06:00) Bangladesh, Bhutan, Novosibirsk',
'UTC+06:30'					=>	'(UTC+06:30) Cocos Islands, Myanmar',
'UTC+07:00'					=>	'(UTC+07:00) Indochina, Krasnoyarsk',
'UTC+08:00'					=>	'(UTC+08:00) Greater China, Australian Western, Irkutsk',
'UTC+08:45'					=>	'(UTC+08:45) Southeastern Western Australia',
'UTC+09:00'					=>	'(UTC+09:00) Japan, Korea, Chita',
'UTC+09:30'					=>	'(UTC+09:30) Australian Central',
'UTC+10:00'					=>	'(UTC+10:00) Australian Eastern, Vladivostok',
'UTC+10:30'					=>	'(UTC+10:30) Lord Howe',
'UTC+11:00'					=>	'(UTC+11:00) Solomon Island, Magadan',
'UTC+11:30'					=>	'(UTC+11:30) Norfolk Island',
'UTC+12:00'					=>	'(UTC+12:00) New Zealand, Fiji, Kamchatka',
'UTC+12:45'					=>	'(UTC+12:45) Chatham Islands',
'UTC+13:00'					=>	'(UTC+13:00) Tonga, Phoenix Islands',
'UTC+14:00'					=>	'(UTC+14:00) Line Islands'

);
