<?php

// Language definitions used in profile.php
$lang_profile = array(

// Navigation and sections
'Profile menu'					=>	'Profiilivalikko',
'Section essentials'			=>	'Yleiset',
'Section personal'				=>	'Henkilötiedot',
'Section messaging'				=>	'Viestintä',
'Section personality'			=>	'Personality',
'Section display'				=>	'Mukauttaminen',
'Section privacy'				=>	'Yksityisyysasetukset',
'Section admin'					=>	'Hallinta',

// Miscellaneous
'Username and pass legend'		=>	'Anna käyttäjänimi ja salasana',
'Personal details legend'		=>	'Enter your personal details',
'Contact details legend'		=>	'Enter your messaging details',
'User activity'					=>	'Käyttäjän aktiivisuus',
'Paginate info'					=>	'Enter the number of topics and posts you wish to view on each page.',

// Password stuff
'Pass key bad'					=>	'The specified password activation key was incorrect or has expired. Please re-request a new password. If that fails, contact the forum administrator at',
'Pass updated'					=>	'Salasanasi on vaihdettu. Voit nyt kirjautua sisään uudella salasanalla.',
'Pass updated redirect'			=>	'Salasana vaihdettu. Uudelleenohjataan …',
'Wrong pass'					=>	'Väärä vanha salasana.',
'Change pass'					=>	'Muuta salasana',
'Change pass legend'			=>	'Syötä ja vahvista uusi salasana',
'Old pass'						=>	'Vanha salasana',
'New pass'						=>	'Uusi salasana',
'Confirm new pass'				=>	'Vahvista uusi salasana',
'Pass info'						=>	'Salasanan täytyy olla vähintään 4 merkkiä pitkä. Isot ja pienet kirjaimet huomioidaan.',

// Email stuff
'Email key bad'					=>	'The specified email activation key was incorrect or has expired. Please re-request change of email address. If that fails, contact the forum administrator at',
'Email updated'					=>	'Sähköpostiosoitteesi on vaihdettu.',
'Activate email sent'			=>	'An email has been sent to the specified address with instructions on how to activate the new email address. If it doesn\'t arrive you can contact the forum administrator at',
'Email legend'					=>	'Anna uusi sähköpostiosoite',
'Email instructions'			=>	'An email will be sent to your new address with an activation link. You must click the link in the email you receive to activate the new address.',
'Change email'					=>	'Vaihda sähköpostiosoite',
'New email'						=>	'Uusi sähköposti',

// Avatar upload stuff
'Avatars disabled'				=>	'The administrator has disabled avatar support.',
'Too large ini'					=>	'Valitsemasi tiedosto on liian suuri llähetettäväksi. Palvelin ei hyväksy lähetyspyyntöäsi.',
'Partial upload'				=>	'Tiedosto lähettäminen epäonnistui. Yritä uudelleen.',
'No tmp directory'				=>	'PHP ei pystynyt tallentamaan tiedostoa.',
'No file'						=>	'Et ole valinnut tiedostoa lähetettäväksi.',
'Bad type'						=>	'The file you tried to upload is not of an allowed type. Allowed types are gif, jpeg and png.',
'Too wide or high'				=>	'The file you tried to upload is wider and/or higher than the maximum allowed',
'Too large'						=>	'The file you tried to upload is larger than the maximum allowed',
'pixels'						=>	'pixels',
'bytes'							=>	'bytes',
'Move failed'					=>	'The server was unable to save the uploaded file. Please contact the forum administrator at',
'Unknown failure'				=>	'An unknown error occurred. Please try again.',
'Avatar upload redirect'		=>	'Avatar uploaded. Redirecting …',
'Avatar deleted redirect'		=>	'Avatar deleted. Redirecting …',
'Avatar desc'					=>	'An avatar is a small image that will be displayed under your username in your posts. It must not be any bigger than',
'Upload avatar'					=>	'Upload avatar',
'Upload avatar legend'			=>	'Enter an avatar file to upload',
'Delete avatar'					=>	'Poista keskustelukuvake', // only for admins
'File'							=>	'Tiedosto',
'Upload'						=>	'Lähetä', // submit button

// Form validation stuff
'Forbidden title'				=>	'The title you entered contains a forbidden word. You must choose a different title.',
'Profile redirect'				=>	'Profiilin tiedot päivitetty. Uudelleenohjataan …',

// Profile display stuff
'Users profile'					=>	'%sn profiili',
'Username info'					=>	'Käyttäjänimet: %s',
'Email info'					=>	'Sähköposti: %s',
'Posts info'					=>	'Viestit: %s',
'Registered info'				=>	'Rekisteröitynyt: %s',
'Last post info'				=>	'Viimeisin viesti: %s',
'Last visit info'				=>	'Käynyt viimeksi: %s',
'Show posts'					=>	'Näytä kaikki viestit',
'Show topics'					=>	'Näytä kaikki aiheet',
'Show subscriptions'			=>	'Näytä kaikki tilaajat',
'Realname'						=>	'Todellinen nimi',
'Location'						=>	'Asuinpaikka',
'Website'						=>	'Internetsivusto',
'Jabber'						=>	'Jabber',
'ICQ'							=>	'ICQ',
'MSN'							=>	'MSN Messenger',
'AOL IM'						=>	'AOL IM',
'Yahoo'							=>	'Yahoo! Messenger',
'Avatar'						=>	'Avatar',
'Signature'						=>	'Allekirjoitus',
'Sig max size'					=>	'Max length: %s characters / Max lines: %s',
'Avatar legend'					=>	'Set your avatar display options',
'Avatar info'					=>	'An avatar is a small image that will be displayed with all your posts. You can upload an avatar by clicking the link below.',
'Change avatar'					=>	'Change avatar',
'Signature legend'				=>	'Compose your signature',
'Signature info'				=>	'A signature is a small piece of text that is attached to your posts. In it, you can enter just about anything you like. Perhaps you would like to enter your favourite quote or your star sign. It\'s up to you! In your signature you can use BBCode if it is allowed in this particular forum. You can see the features that are allowed/enabled listed below whenever you edit your signature.',
'Sig preview'					=>	'Nykyisen allekirjoituksen esikatselu:',
'No sig'						=>	'Profissasi ei ole määritelty allekirjoitusta.',
'Signature quote/code/list/h'	=>	'The quote, code, list, and heading BBCodes are not allowed in signatures.',
'Topics per page'				=>	'Aiheet',
'Posts per page'				=>	'Viestit',
'Leave blank'					=>	'Leave blank to use forum default.',
'Subscription legend'			=>	'Set your subscription options',
'Notify full'					=>	'Include a plain text version of new posts in subscription notification emails.',
'Auto notify full'				=>	'Automatically subscribe to every topic you post in.',
'Show smilies'					=>	'Show smilies as graphic icons.',
'Show images'					=>	'Näytä kuvat viesteissä.',
'Show images sigs'				=>	'Show images in user signatures.',
'Show avatars'					=>	'Show user avatars in posts.',
'Show sigs'						=>	'Näytä käyttäjän allekirjoitukset.',
'Style legend'					=>	'Select your preferred style',
'Styles'						=>	'Tyylit',
'Admin note'					=>	'Admin note',
'Pagination legend'				=>	'Enter your pagination options',
'Post display legend'			=>	'Set your options for viewing posts',
'Post display info'				=>	'If you are on a slow connection, disabling these options, particularly showing images in posts and signatures, will make pages load faster.',
'Instructions'					=>	'When you update your profile, you will be redirected back to this page.',

// Administration stuff
'Group membership legend'		=>	'Valitse käyttäjäryhmä',
'Save'							=>	'Tallenna',
'Set mods legend'				=>	'Aseta moderaattorin oikeudet',
'Moderator in info'				=>	'Choose which forums this user should be allowed to moderate. Note: This only applies to moderators. Administrators always have full permissions in all forums.',
'Update forums'					=>	'Päivitä keskustelualueet',
'Delete ban legend'				=>	'Poista (toiminto vain pääkäyttäjälle) tai bannaa käyttäjä',
'Delete user'					=>	'Poista käyttäjä',
'Ban user'						=>	'Bannaa käyttäjä',
'Confirm delete legend'			=>	'Tärkeää: lue ennenkuin poistat käyttäjän',
'Confirm delete user'			=>	'Vahvista käyttäjän poistaminen',
'Confirmation info'				=>	'Please confirm that you want to delete the user', // the username will be appended to this string
'Delete warning'				=>	'Warning! Deleted users and/or posts cannot be restored. If you choose not to delete the posts made by this user, the posts can only be deleted manually at a later time.',
'Delete posts'					=>	'Delete any posts and topics this user has made.',
'Delete'						=>	'Delete', // submit button (confirm user delete)
'User delete redirect'			=>	'User deleted. Redirecting …',
'Group membership redirect'		=>	'Group membership saved. Redirecting …',
'Update forums redirect'		=>	'Forum moderator rights updated. Redirecting …',
'Ban redirect'					=>	'Uudelleenohjataan …',
'No delete admin message'		=>	'Administrators cannot be deleted. In order to delete this user, you must first move him/her to a different user group.',

);