<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Hae k&auml;ytt&auml;ji&auml;',
'No search permission'				=>	'Sinulla ei ole tarvittavia oikeuksia k&auml;ytt&auml;&auml; hakutoimintoa.',
'Search flood'						=>	'Aikaviive edellisen ja uuden hausi v&auml;lill&auml; oli liian lyhyt. Odota %s sekuntia ja yrit&auml; sitten uudelleen.',
'Search'							=>	'Haku',
'Search criteria legend'			=>	'Valitse hakukriteeri',
'Search info'						=>	'To search by keyword, enter a term or terms to search for. Separate terms with spaces. Use AND, OR and NOT to refine your search. To search by author enter the username of the author whose posts you wish to search for. Use wildcard character * for partial matches.',
'Keyword search'					=>	'Haku avainsanoilla',
'Author search'						=>	'Hae julkaisijaa nimimerkill&auml;',
'Search in legend'					=>	'Valitse haun kohde',
'Search in info'					=>	'Choose in which forum you would like to search and if you want to search in topic subjects, message text or both.',
'Forum search'						=>	'Keskustelualue',
'All forums'						=>	'Kaikki keskustelualueet',
'Search in'							=>	'Etsi kohteesta',
'Message and subject'				=>	'Viestin sis&auml;lt&ouml; ja aiheen otsikko',
'Message only'						=>	'Vain viestin sis&auml;lt&ouml;',
'Topic only'						=>	'Vain aiheen otsikkko',
'Sort by'							=>	'Lajittelu',
'Sort order'						=>	'Lajittelujj&auml;rjestys',
'Search results legend'				=>	'Valitse miten haun tulokset n&auml;ytet&auml;&auml;n',
'Search results info'				=>	'Voit valita miten haun tulokset n&auml;ytet&auml;&auml;n ja lajitellaan.',
'Sort by post time'					=>	'Julkaisuaika',
'Sort by author'					=>	'Julkaisija',
'Sort by subject'					=>	'Otsikko',
'Sort by forum'						=>	'Keskustelualue',
'Ascending'							=>	'Nouseva',
'Descending'						=>	'Laskeva',
'Show as'							=>	'Show results as',
'Show as topics'					=>	'Aiheet',
'Show as posts'						=>	'Viestit',

// Results
'Search results'					=>	'Haun tulokset',
'Search topics'						=>	'Hae aiheita',
'Search posts'						=>	'Hae viestej&auml;',
'Quick search show_new'				=>	'Uusi',
'Quick search show_recent'			=>	'Aktiivinen',
'Quick search show_unanswered'		=>	'Vastaamaton',
'Quick search show_replies'			=>	'Julkaistu',
'Quick search show_user_topics'		=>	'By %s',
'Quick search show_user_posts'		=>	'By %s',
'Quick search show_subscriptions'	=>	'Tilaaja(t): %s',
'By keywords show as topics'		=>	'With posts with keywords \'%s\'',
'By keywords show as posts'			=>	'With keywords \'%s\'',
'By user show as topics'			=>	'With posts by %s',
'By user show as posts'				=>	'By %s',
'By both show as topics'			=>	'With keywords \'%s\' in posts by %s',
'By both show as posts'				=>	'With keywords \'%s\' by %s',
'No terms'							=>	'You have to enter at least one keyword and/or an author to search for.',
'No hits'							=>	'Your search returned no hits.',
'No user posts'						=>	'There are no posts by this user in this forum.',
'No user topics'					=>	'There are no topics by this user in this forum.',
'No subscriptions'					=>	'This user is currently not subscribed to any topics.',
'No new posts'						=>	'Ei uusia aiheita tai viestej&auml; viime k&auml;yntisi j&auml;lkeen.',
'No recent posts'					=>	'Ei uusia viestej&auml; kuluneen 24 tunnin sis&auml;ll&auml;.',
'No unanswered'						=>	'Keskustelualueella ei ole vastaamattomia viestej&auml;.',
'Go to post'						=>	'Siirry viestiin',
'Go to topic'						=>	'Siirry aiheeseen'

);
