<?php

// Language definitions used in search.php
$lang_search = array(

// The search form
'User search'						=>	'Hae k&auml;ytt&auml;ji&auml;',
'No search permission'				=>	'Sinulla ei ole tarvittavia oikeuksia k&auml;ytt&auml;&auml; hakutoimintoa.',
'Search flood'						=>	'Aikaviive edellisen ja uuden hausi v&auml;lill&auml; oli liian lyhyt. Odota %s sekuntia ja yrit&auml; sitten uudelleen.',
'Search'							=>	'Haku',
'Search criteria legend'			=>	'Valitse hakukriteeri',
'Search info'						=>	' To search by keyword, enter a term or terms to search for. Separate terms with spaces. Use AND, OR and NOT to refine your search. To search by author enter the username of the author whose posts you wish to search for. Use wildcard character * for partial matches.',
'Keyword search'					=>	'Haku avainsanoilla',
'Author search'						=>	'Hae julkaisijaa nimimerkill&auml;',
'Search in legend'					=>	'Valitse haun kohde',
'Search in info'					=>	'Choose in which forum you would like to search and if you want to search in topic subjects, message text or both.',
'Forum search'						=>	'Keskustelualue',
'All forums'						=>	'Kaikki keskustelualueet',
'Search in'							=>	'Etsi kohteesta',
'Message and subject'				=>	'Viestin sis&auml;lt&ouml; ja aiheen otsikko',
'Message only'						=>	'Vain viestin sis&auml;lt&ouml;',
'Topic only'						=>	'Vain aiheen otsikkko',
'Sort by'							=>	'Lajittelu',
'Sort order'						=>	'Lajittelujj&auml;rjestys',
'Search results legend'				=>	'Valitse miten haun tulokset n&auml;ytet&auml;&auml;n',
'Search results info'				=>	'Voit valita miten haun tulokset n&auml;ytet&auml;&auml;n ja lajitellaan.',
'Sort by post time'					=>	'Julkaisuaika',
'Sort by author'					=>	'Julkaisija',
'Sort by subject'					=>	'Otsikko',
'Sort by forum'						=>	'Keskustelualue',
'Ascending'							=>	'Nouseva',
'Descending'						=>	'Laskeva',
'Show as'							=>	'Tulokset n&auml;ytet&auml;&auml;n:',
'Show as topics'					=>	'Aiheet',
'Show as posts'						=>	'Viestit',

// Results
'Search results'					=>	'Haun tulokset',
'Search topics'						=>	'Hae aiheita',
'Search posts'						=>	'Hae viestej&auml;',
'Quick search show_new'				=>	'Uusi',
'Quick search show_recent'			=>	'Aktiivinen',
'Quick search show_unanswered'		=>	'Vastaamaton',
'Quick search show_replies'			=>	'Julkaistu',
'Quick search show_user_topics'		=>	'K&auml;ytt&auml;j&auml;lt&auml; %s',
'Quick search show_user_posts'		=>	'K&auml;ytt&auml;j&auml;lt&auml; %s',
'Quick search show_subscriptions'	=>	'Tilaaja(t): %s',
'By keywords show as topics'		=>	'Viesteiss&auml; jossa avainsana %s',
'By keywords show as posts'			=>	'With keywords %s',
'By user show as topics'			=>	'%s viesteiss&auml;',
'By user show as posts'				=>	'K&auml;ytt&auml;j&auml;lt&auml; %s',
'By both show as topics'			=>	'Avainsanoissa %s  viesteiss&auml; k&auml;ytt&auml;j&auml;lt&auml; %s',
'By both show as posts'				=>	'Avainsanoilla %s k&auml;ytt&auml;j&auml;lt&auml; %s',
'No terms'							=>	'Sinun t&auml;ytyy antaa ainakin yksi avainsana ja / tai k&auml;ytt&auml;j&auml;n nimimerkki suorittaaksesi haun.',
'No hits'							=>	'Haku ei tuottanut yht&auml;&auml;n osumaa.',
'No user posts'						=>	'Keskustelualueella ei ole uusia viestej&auml; t&auml;lt&auml; k&auml;ytt&auml;j&auml;lt&auml;.',
'No user topics'					=>	'Keskustelualueella ei ole uusia aiheita t&auml;lt&auml; k&auml;ytt&auml;j&auml;lt&auml;.',
'No subscriptions'					=>	'K&auml;ytt&auml;j&auml; ei ole t&auml;ll&auml; hetkell&auml; tilannut yht&auml;&auml;n aihetta.',
'No new posts'						=>	'Ei uusia aiheita tai viestej&auml; viime k&auml;yntisi j&auml;lkeen.',
'No recent posts'					=>	'Ei uusia viestej&auml; kuluneen 24 tunnin sis&auml;ll&auml;.',
'No unanswered'						=>	'Keskustelualueella ei ole vastaamattomia viestej&auml;.',
'Go to post'						=>	'Siirry viestiin',
'Go to topic'						=>	'Siirry aiheeseen'

);
